In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline 

In [2]:
df=pd.read_csv("social_media_addiction_mental_wellbeing.csv")

In [3]:
df.head(10)

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
0,USR00001,30,Male,Working Professional,In a Relationship,YouTube,2.9,4,3,No,...,1.7,6.5,8.5,5.3,3.7,3.8,5.8,3.1,7.3,Low
1,USR00002,19,Male,Student,Married,Instagram,4.8,1,0,NaN,...,7.0,7.5,7.8,5.5,4.0,1.8,0.9,3.3,4.1,Severe
2,USR00003,40,Male,Student,In a Relationship,YouTube,NaN,4,5,No,...,5.6,5.3,6.3,NaN,5.8,2.8,0.0,1.5,5.6,High
3,USR00004,37,Female,Student,Married,Facebook,7.7,2,3,Yes,...,5.6,1.4,3.9,6.1,5.5,3.6,1.0,3.9,4.3,Severe
4,USR00005,18,Non-binary,Student,In a Relationship,TikTok,4.6,3,0,No,...,4.0,NaN,5.7,5.0,3.8,3.2,0.6,1.0,6.6,Moderate
5,USR00006,34,Male,Working Professional,Married,YouTube,1.2,1,3,No,...,5.0,7.9,NaN,5.6,2.8,5.6,4.1,1.5,7.7,Low
6,USR00007,38,Female,Student,In a Relationship,Facebook,5.0,4,4,Yes,...,7.2,0.5,4.8,8.2,6.8,5.4,3.2,3.7,5.5,High
7,USR00008,22,Female,Unemployed,Single,Twitter/X,3.4,5,2,No,...,3.1,2.9,3.8,10.0,6.8,6.7,NaN,6.6,6.2,Moderate
8,USR00009,43,Female,Student,Single,YouTube,9.2,4,2,No,...,3.8,5.1,3.2,5.7,3.2,5.4,4.8,0.6,3.4,Severe
9,USR00010,40,Male,Student,Single,Instagram,6.9,2,5,Yes,...,3.9,8.1,7.4,5.8,6.4,7.2,4.6,0.0,7.7,Low


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   User_ID                       1500 non-null   object 
 1   Age                           1500 non-null   int64  
 2   Gender                        1447 non-null   object 
 3   Occupation                    1455 non-null   object 
 4   Relationship_Status           1449 non-null   object 
 5   Primary_Platform              1447 non-null   object 
 6   Daily_Usage_Hours             1444 non-null   float64
 7   Platforms_Used_Count          1500 non-null   int64  
 8   Posts_Per_Week                1500 non-null   int64  
 9   Late_Night_Usage              1450 non-null   object 
 10  First_Check_Morning           1500 non-null   object 
 11  Notifications_Per_Day         1500 non-null   int64  
 12  FOMO_Score                    1445 non-null   float64
 13  Soc

In [5]:
df.isnull().sum()

User_ID                          0
Age                              0
Gender                          53
Occupation                      45
Relationship_Status             51
Primary_Platform                53
Daily_Usage_Hours               56
Platforms_Used_Count             0
Posts_Per_Week                   0
Late_Night_Usage                50
First_Check_Morning              0
Notifications_Per_Day            0
FOMO_Score                      55
Social_Comparison_Score         51
Validation_Seeking_Score        58
Scroll_Without_Purpose           0
Tried_To_Cut_Back               41
Failed_To_Cut_Back              43
Anxiety_Score                   48
Depression_Score                55
Loneliness_Score                55
Self_Esteem_Score               69
Sleep_Quality_Score             68
Sleep_Hours                     62
Productivity_Loss_Score         51
Offline_Relationship_Quality    70
Physical_Activity_Hrs_Week      51
Screen_Free_Time_Hrs            60
Mental_Wellbeing_Sco

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.compose import ColumnTransformer

In [8]:
X = df.drop(columns=["User_ID","Addiction_Level"])
y= df["Addiction_Level"]

In [9]:
numeric_columns = X.select_dtypes(include="number").columns

In [10]:
numeric_columns

Index(['Age', 'Daily_Usage_Hours', 'Platforms_Used_Count', 'Posts_Per_Week',
       'Notifications_Per_Day', 'FOMO_Score', 'Social_Comparison_Score',
       'Validation_Seeking_Score', 'Scroll_Without_Purpose', 'Anxiety_Score',
       'Depression_Score', 'Loneliness_Score', 'Self_Esteem_Score',
       'Sleep_Quality_Score', 'Sleep_Hours', 'Productivity_Loss_Score',
       'Offline_Relationship_Quality', 'Physical_Activity_Hrs_Week',
       'Screen_Free_Time_Hrs', 'Mental_Wellbeing_Score'],
      dtype='object')

In [11]:
categorical_columns = X.select_dtypes(include=["string","category","object"]).columns

In [12]:
categorical_columns

Index(['Gender', 'Occupation', 'Relationship_Status', 'Primary_Platform',
       'Late_Night_Usage', 'First_Check_Morning', 'Tried_To_Cut_Back',
       'Failed_To_Cut_Back'],
      dtype='object')

In [13]:
numeric_pipeline = Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler",StandardScaler())
])

In [14]:
categorical_pipeline = Pipeline([
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])

In [15]:
preprocessor = ColumnTransformer([
    ("numeric",numeric_pipeline,numeric_columns),
    ("categoric",categorical_pipeline,categorical_columns)
])


In [16]:
model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("regression",LogisticRegression(max_iter=200,class_weight="balanced",random_state=15))
])

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=15)

In [18]:
model_pipeline.fit(X_train,y_train)

,steps,"[('preprocessor', ...), ('regression', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('numeric', ...), ('categoric', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [19]:
y_pred = model_pipeline.predict(X_test)

In [20]:
score = accuracy_score(y_pred,y_test)
print("Accuracy : ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix : ",confusion_matrix(y_pred,y_test))

Accuracy :  0.7888888888888889
              precision    recall  f1-score   support

        High       0.71      0.73      0.72       102
         Low       0.84      0.87      0.85       124
    Moderate       0.73      0.73      0.73       135
      Severe       0.90      0.84      0.87        89

    accuracy                           0.79       450
   macro avg       0.80      0.79      0.79       450
weighted avg       0.79      0.79      0.79       450

Confusion Matrix :  [[ 74   0  20   8]
 [  0 108  16   0]
 [ 16  21  98   0]
 [ 14   0   0  75]]


In [21]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold

In [22]:
penalty = ["l1","l2","elasticnet"]
solver = ['liblinear', 'newton-cg', 'sag', 'saga' , 'lbfgs']
c_values = [100,10,1,0.1,0.01]

In [23]:
params = dict(regression__penalty = penalty,regression__C=c_values,regression__solver=solver)

In [24]:
cv= StratifiedKFold()

In [25]:
grid = GridSearchCV(estimator=model_pipeline,param_grid=params,cv=cv,scoring="accuracy",n_jobs=-1)

In [26]:
grid.fit(X_train,y_train)

,estimator,Pipeline(step...m_state=15))])
,param_grid,"{'regression__C': [100, 10, ...], 'regression__penalty': ['l1', 'l2', ...], 'regression__solver': ['liblinear', 'newton-cg', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,transformers,"[('numeric', ...), ('categoric', ...)]"


In [27]:
y_pred = grid.predict(X_test)

In [28]:
score = accuracy_score(y_pred,y_test)
print("Accuracy : ",score)
print(classification_report(y_pred,y_test))
print("Confusion Matrix : ",confusion_matrix(y_pred,y_test))

Accuracy :  0.7822222222222223
              precision    recall  f1-score   support

        High       0.71      0.72      0.71       103
         Low       0.83      0.86      0.85       124
    Moderate       0.72      0.72      0.72       134
      Severe       0.90      0.84      0.87        89

    accuracy                           0.78       450
   macro avg       0.79      0.79      0.79       450
weighted avg       0.78      0.78      0.78       450

Confusion Matrix :  [[ 74   0  21   8]
 [  0 107  17   0]
 [ 16  22  96   0]
 [ 14   0   0  75]]
